# Generated by Django 6.0 on 2026-05-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('otp', models.CharField(max_length=6)),
                ('otp_created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=200, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('illness_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
