# Generated by Django 6.0 on 2026-05-10 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_temporaryregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryregistration',
            name='illness_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='illness_description',
        ),
    ]
