# Generated by Django 6.0 on 2026-05-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_temporaryregistration_illness_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryregistration',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='user',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='temporaryregistration',
            name='practicing_year_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='practicing_year_from',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
