# Generated by Django 6.0 on 2026-03-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_canceled_by_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
